ingestion:
  to_feature_store: True
test_fraction: 0.3
feature_selection: "rfe"
random_state: 2021
target_column: "target"
baseline_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 2021