artifact_location: file:///Users/afonsogamito/Documents/NOVA- 2ยบ Semester/ML Operations/mlopsproject/mlruns/190429715794963139
creation_time: 1750882810130
experiment_id: '190429715794963139'
last_update_time: 1750882810130
lifecycle_stage: active
name: mlopsproject
